title: "Programação Funcional" # the name of your site, e.g. ACME Corp.
baseurl: /programacao-funcional/website

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]

plugins:
  - jekyll-postcss